[phases.setup]
nixPkgs = ["nodejs-18_x", "python39"]

[phases.install] 
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "chmod +x start.sh"
]

[phases.start]
cmd = "bash start.sh"

[variables]
PORT = "8000"