[variables]
NIXPACKS_PYTHON_VERSION = "3.9"
PORT = "8000"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip"]
nixLibs = ["zlib", "openssl"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "chmod +x start.sh",
    "cd project && npm install && npm run build"
]

[phases.start]
cmd = "python api_server.py"