[phases.setup]
nixPkgs = ['nodejs', 'python311']

[phases.build]
cmds = [
    'cd project && npm install',
    'cd project && npm run build',
    'python build_frontend.py'
]

[phases.start]
cmd = 'python api_server.py'